// Complete CALABARZON (Region 4A) Location Database
// This includes all 5 provinces and their respective cities/municipalities and barangays
const philippineLocations = {
  "Region 4A CALABARZON": {
    Cavite: {
      "Bacoor City": [
        "Alima",
        "Aniban I",
        "Aniban II",
        "Aniban III",
        "Aniban IV",
        "Aniban V",
        "Banalo",
        "Bayanan",
        "Campo Santo",
        "Daang Bukid",
        "Digman",
        "Dulong Bayan",
        "Ginintuang Silahis",
        "Habay I",
        "Habay II",
        "Kaingin",
        "Ligas I",
        "Ligas II",
        "Ligas III",
        "Mabolo I",
        "Mabolo II",
        "Mabolo III",
        "Maliksi I",
        "Maliksi II",
        "Maliksi III",
        "Mambog I",
        "Mambog II",
        "Mambog III",
        "Mambog IV",
        "Mambog V",
        "Molino I",
        "Molino II",
        "Molino III",
        "Molino IV",
        "Molino V",
        "Molino VI",
        "Molino VII",
        "Niog I",
        "Niog II",
        "Niog III",
        "Panapaan I",
        "Panapaan II",
        "Panapaan III",
        "Panapaan IV",
        "Panapaan V",
        "Panapaan VI",
        "Panapaan VII",
        "Panapaan VIII",
        "Queen's Row Central",
        "Queen's Row East",
        "Queen's Row West",
        "Real I",
        "Real II",
        "Salinas I",
        "Salinas II",
        "Salinas III",
        "Salinas IV",
        "San Nicolas I",
        "San Nicolas II",
        "San Nicolas III",
        "Springville",
        "Tabing Dagat",
        "Talaba I",
        "Talaba II",
        "Talaba III",
        "Talaba IV",
        "Talaba V",
        "Talaba VI",
        "Talaba VII",
        "Zapote I",
        "Zapote II",
        "Zapote III",
        "Zapote IV",
        "Zapote V",
      ],
      "Cavite City": [
        "Barangay 1",
        "Barangay 2",
        "Barangay 3",
        "Barangay 4",
        "Barangay 5",
        "Barangay 6",
        "Barangay 7",
        "Barangay 8",
        "Barangay 9",
        "Barangay 10",
        "Barangay 11",
        "Barangay 12",
        "Barangay 13",
        "Barangay 14",
        "Barangay 15",
        "Barangay 16",
        "Barangay 17",
        "Barangay 18",
        "Barangay 19",
        "Barangay 20",
        "Barangay 21",
        "Barangay 22",
        "Barangay 23",
        "Barangay 24",
        "Barangay 25",
        "Barangay 26",
        "Barangay 27",
        "Barangay 28",
        "Barangay 29",
        "Barangay 30",
        "Barangay 31",
        "Barangay 32",
        "Barangay 33",
        "Barangay 34",
        "Barangay 35",
        "Barangay 36",
        "Barangay 37",
        "Barangay 38",
        "Barangay 39",
        "Barangay 40",
        "Barangay 41",
        "Barangay 42",
        "Barangay 43",
        "Barangay 44",
        "Barangay 45",
        "Barangay 46",
        "Barangay 47",
        "Barangay 48",
        "Barangay 49",
        "Barangay 50",
        "Barangay 51",
        "Barangay 52",
        "Barangay 53",
        "Barangay 54",
        "Barangay 55",
        "Barangay 56",
        "Barangay 57",
        "Barangay 58",
        "Barangay 59",
        "Barangay 60",
        "Barangay 61",
        "Barangay 62",
        "Barangay 63",
        "Barangay 64",
        "Barangay 65",
        "Barangay 66",
        "Barangay 67",
        "Barangay 68",
        "Barangay 69",
        "Barangay 70",
        "Barangay 71",
        "Barangay 72",
        "Barangay 73",
        "Barangay 74",
        "Barangay 75",
        "Barangay 76",
        "Barangay 77",
        "Barangay 78",
        "Barangay 79",
        "Barangay 80",
        "Barangay 81",
        "Barangay 82",
        "Barangay 83",
        "Barangay 84",
      ],
      "Dasmariñas City": [
        "Bagong Bayan",
        "Burol I",
        "Burol II",
        "Burol III",
        "Datu Esmael",
        "Fatima I",
        "Fatima II",
        "Fatima III",
        "Langkaan I",
        "Langkaan II",
        "Luzviminda I",
        "Luzviminda II",
        "Paliparan I",
        "Paliparan II",
        "Paliparan III",
        "Sabang",
        "Salawag",
        "Salitran I",
        "Salitran II",
        "Salitran III",
        "Salitran IV",
        "Sampaloc I",
        "Sampaloc II",
        "Sampaloc III",
        "Sampaloc IV",
        "San Agustin I",
        "San Agustin II",
        "San Agustin III",
        "San Dionisio",
        "San Esteban",
        "San Jose",
        "San Juan I",
        "San Juan II",
        "San Luis I",
        "San Luis II",
        "San Miguel",
        "San Simon",
        "Santa Cruz I",
        "Santa Cruz II",
        "Santa Jenny",
        "Victoria Reyes",
        "Zone I",
        "Zone II",
        "Zone III",
        "Zone IV",
      ],
      "General Trias City": [
        "Alingaro",
        "Arnaldo Poblacion",
        "Bacao I",
        "Bacao II",
        "Bagumbayan Poblacion",
        "Biclatan",
        "Buenavista I",
        "Buenavista II",
        "Buenavista III",
        "Corregidor Poblacion",
        "Dulong Bayan Poblacion",
        "Gov. Ferrer Poblacion",
        "Javalera",
        "Manggahan",
        "Navarro",
        "Ninety Six",
        "Panungyanan",
        "Pasong Camachile I",
        "Pasong Camachile II",
        "Pasong Kawayan I",
        "Pasong Kawayan II",
        "Pinagtipunan",
        "Prinza Poblacion",
        "San Francisco",
        "San Gabriel Poblacion",
        "San Juan I",
        "San Juan II",
        "Santa Clara",
        "Santiago",
        "Tapia",
        "Tejero",
        "Vibora Poblacion",
      ],
      "Imus City": [
        "Alapan I-A",
        "Alapan I-B",
        "Alapan I-C",
        "Alapan II-A",
        "Alapan II-B",
        "Anabu I-A",
        "Anabu I-B",
        "Anabu I-C",
        "Anabu I-D",
        "Anabu I-E",
        "Anabu I-F",
        "Anabu I-G",
        "Anabu II-A",
        "Anabu II-B",
        "Anabu II-C",
        "Anabu II-D",
        "Anabu II-E",
        "Anabu II-F",
        "Bayan Luma I",
        "Bayan Luma II",
        "Bayan Luma III",
        "Bayan Luma IV",
        "Bayan Luma V",
        "Bayan Luma VI",
        "Bayan Luma VII",
        "Bayan Luma VIII",
        "Bayan Luma IX",
        "Bucandala I",
        "Bucandala II",
        "Bucandala III",
        "Bucandala IV",
        "Bucandala V",
        "Buhay na Tubig",
        "Carsadang Bago I",
        "Carsadang Bago II",
        "Magdalo",
        "Maharlika",
        "Malagasang I-A",
        "Malagasang I-B",
        "Malagasang I-C",
        "Malagasang I-D",
        "Malagasang I-E",
        "Malagasang I-F",
        "Malagasang I-G",
        "Malagasang II-A",
        "Malagasang II-B",
        "Malagasang II-C",
        "Malagasang II-D",
        "Malagasang II-E",
        "Malagasang II-F",
        "Medicion I-A",
        "Medicion I-B",
        "Medicion I-C",
        "Medicion I-D",
        "Medicion II-A",
        "Medicion II-B",
        "Medicion II-C",
        "Medicion II-D",
        "Medicion II-E",
        "Palico I",
        "Palico II",
        "Palico III",
        "Palico IV",
        "Panacan I",
        "Panacan II",
        "Panacan III",
        "Poblacion I-A",
        "Poblacion I-B",
        "Poblacion I-C",
        "Poblacion II-A",
        "Poblacion II-B",
        "Poblacion III-A",
        "Poblacion III-B",
        "Poblacion IV-A",
        "Poblacion IV-B",
        "Poblacion IV-C",
        "Poblacion IV-D",
        "Putatan",
        "Tanzang Luma I",
        "Tanzang Luma II",
        "Tanzang Luma III",
        "Tanzang Luma IV",
        "Tanzang Luma V",
        "Tanzang Luma VI",
        "Toclong I-A",
        "Toclong I-B",
        "Toclong I-C",
        "Toclong II-A",
        "Toclong II-B",
      ],
      "Tagaytay City": [
        "Asisan",
        "Bagong Tubig",
        "Calabuso",
        "Dapdap East",
        "Dapdap West",
        "Francisco",
        "Guinhawa North",
        "Guinhawa South",
        "Iruhin Central",
        "Iruhin East",
        "Iruhin South",
        "Iruhin West",
        "Kaybagal Central",
        "Kaybagal North",
        "Kaybagal South",
        "Mag-Asawang Ilat",
        "Maharlika East",
        "Maharlika West",
        "Maitim 2nd Central",
        "Maitim 2nd East",
        "Maitim 2nd West",
        "Mendez Crossing East",
        "Mendez Crossing West",
        "Neogan",
        "Patutong Malaki North",
        "Patutong Malaki South",
        "Sambong",
        "San Jose",
        "Silang Junction North",
        "Silang Junction South",
        "Sungay East",
        "Sungay West",
        "Tolentino East",
        "Tolentino West",
        "Zambal",
      ],
      "Trece Martires City": [
        "Aguado",
        "Cabezas",
        "Cabuco",
        "Conchu",
        "De Ocampo",
        "Gregorio",
        "Hugo Perez",
        "Inocencio",
        "Lapidario",
        "Lullutan",
        "Perez",
        "Quintero",
        "San Agustin",
      ],
      Silang: [
        "Adlas",
        "Anahaw I",
        "Anahaw II",
        "Balite I",
        "Balite II",
        "Biga I",
        "Biga II",
        "Biluso",
        "Bucal",
        "Bulihan",
        "Cabangaan",
        "Calubcub I",
        "Calubcub II",
        "Carmen",
        "Diezmo",
        "Lalaan I",
        "Lalaan II",
        "Litlit",
        "Maguyam",
        "Malabag",
        "Munting Ilog",
        "Poblacion",
        "Pulong Buhangin",
        "Pulong Saging",
        "Sabutan",
        "San Vicente I",
        "San Vicente II",
        "Santol",
        "Tartaria",
        "Tibig",
        "Tubigan",
      ],
      Carmona: [
        "Bancal",
        "Barangay 1",
        "Barangay 2",
        "Barangay 3",
        "Barangay 4",
        "Barangay 5",
        "Barangay 6",
        "Barangay 7",
        "Lantic",
        "Maduya",
        "Mabuhay",
      ],
      "General Mariano Alvarez": [
        "Barangay 1",
        "Barangay 2",
        "Barangay 3",
        "Barangay 4",
        "Barangay 5",
        "Barangay 6",
        "Barangay 7",
        "Barangay 8",
        "Barangay 9",
        "Barangay 10",
        "Barangay 11",
        "Barangay 12",
        "Barangay 13",
        "Barangay 14",
        "Barangay 15",
        "Barangay 16",
        "Barangay 17",
        "Barangay 18",
        "Barangay 19",
        "Barangay 20",
        "Barangay 21",
        "Barangay 22",
        "Barangay 23",
        "Barangay 24",
        "Barangay 25",
        "Barangay 26",
        "Barangay 27",
      ],
      Kawit: [
        "Binakayan-Kanluran",
        "Binakayan-Silangan",
        "Congbalay",
        "Kaingen",
        "Magdalo",
        "Panamitan",
        "Poblacion",
        "Pulvorista",
        "San Sebastian",
        "Santa Isabel",
        "Tabon I",
        "Tabon II",
        "Tabon III",
      ],
      Noveleta: [
        "Dalahican",
        "Poblacion",
        "Salinas",
        "San Antonio I",
        "San Antonio II",
        "San Juan I",
        "San Juan II",
        "San Rafael I",
        "San Rafael II",
        "San Rafael III",
        "San Rafael IV",
        "Santa Rosa I",
        "Santa Rosa II",
      ],
      Rosario: [
        "Kanluran",
        "Ligtong I",
        "Ligtong II",
        "Ligtong III",
        "Ligtong IV",
        "Muzon I",
        "Muzon II",
        "Poblacion",
        "Sapa I",
        "Sapa II",
        "Sapa III",
        "Sapa IV",
        "Silangan I",
        "Silangan II",
        "Tejeros Convention",
        "Wawa I",
        "Wawa II",
      ],
      Tanza: [
        "Amaya I",
        "Amaya II",
        "Amaya III",
        "Amaya IV",
        "Amaya V",
        "Amaya VI",
        "Amaya VII",
        "Bagtas",
        "Balsahan",
        "Bucana",
        "Capipisa",
        "Daang Amaya I",
        "Daang Amaya II",
        "Daang Amaya III",
        "Halayhay",
        "Julugan I",
        "Julugan II",
        "Julugan III",
        "Julugan IV",
        "Julugan V",
        "Julugan VI",
        "Julugan VII",
        "Julugan VIII",
        "Lambingan",
        "Mulawin",
        "Paradahan I",
        "Paradahan II",
        "Poblacion I",
        "Poblacion II",
        "Poblacion III",
        "Poblacion IV",
        "Sahud-Ulan",
        "Santol",
        "Tres Cruses",
      ],
      Mendez: [
        "Anuling Cerca I",
        "Anuling Cerca II",
        "Asis I",
        "Asis II",
        "Asis III",
        "Banaba Cerca",
        "Banaba Lejos",
        "Bukal",
        "Galicia I",
        "Galicia II",
        "Galicia III",
        "Galicia IV",
        "Poblacion I",
        "Poblacion II",
        "Poblacion III",
        "Poblacion IV",
        "Tubigan",
      ],
      Indang: [
        "Alulod",
        "Banaba Cerca",
        "Banaba Lejos",
        "Buna Cerca",
        "Buna Lejos I",
        "Buna Lejos II",
        "Calumpang Cerca",
        "Calumpang Lejos I",
        "Calumpang Lejos II",
        "Daine I",
        "Daine II",
        "Guyam Malaki",
        "Guyam Munti",
        "Harasan",
        "Kaytambog",
        "Limbon",
        "Lumampong Balagbag",
        "Lumampong Halayhay",
        "Mahabang Parang",
        "Poblacion I",
        "Poblacion II",
        "Poblacion III",
        "Tambo Kulit",
        "Tambo Malaki",
        "Tambo Munti",
      ],
      Naikangan: [
        "Bucana-Ibaba",
        "Bucana-Ilayang",
        "Calero",
        "Labac",
        "Lalaan",
        "Palangue I",
        "Palangue II",
        "Palangue III",
        "Poblacion East",
        "Poblacion West",
        "Sabang",
        "Timalan Balsahan",
        "Timalan Concepcion",
      ],
      Alfonso: [
        "Barangay I",
        "Barangay II",
        "Barangay III",
        "Barangay IV",
        "Barangay V",
        "Barangay VI",
        "Barangay VII",
        "Barangay VIII",
        "Barangay IX",
        "Barangay X",
        "Barangay XI",
        "Barangay XII",
        "Barangay XIII",
        "Barangay XIV",
        "Barangay XV",
        "Barangay XVI",
        "Barangay XVII",
        "Barangay XVIII",
        "Barangay XIX",
        "Barangay XX",
        "Barangay XXI",
        "Barangay XXII",
        "Barangay XXIII",
        "Barangay XXIV",
        "Barangay XXV",
        "Barangay XXVI",
        "Barangay XXVII",
        "Barangay XXVIII",
        "Barangay XXIX",
        "Barangay XXX",
      ],
      Amadeo: [
        "Barangay I",
        "Barangay II",
        "Barangay III",
        "Barangay IV",
        "Barangay V",
        "Barangay VI",
        "Barangay VII",
        "Barangay VIII",
        "Barangay IX",
        "Barangay X",
        "Barangay XI",
        "Barangay XII",
        "Barangay XIII",
        "Barangay XIV",
        "Barangay XV",
        "Barangay XVI",
        "Barangay XVII",
        "Barangay XVIII",
        "Barangay XIX",
        "Barangay XX",
        "Barangay XXI",
        "Barangay XXII",
        "Barangay XXIII",
      ],
      "General Emilio Aguinaldo": [
        "Barangay I",
        "Barangay II",
        "Barangay III",
        "Barangay IV",
        "Barangay V",
        "Barangay VI",
        "Barangay VII",
        "Barangay VIII",
        "Barangay IX",
        "Barangay X",
        "Barangay XI",
        "Barangay XII",
        "Barangay XIII",
        "Barangay XIV",
        "Barangay XV",
        "Barangay XVI",
        "Barangay XVII",
        "Barangay XVIII",
        "Barangay XIX",
        "Barangay XX",
        "Barangay XXI",
        "Barangay XXII",
      ],
      Magallanes: [
        "Barangay I",
        "Barangay II",
        "Barangay III",
        "Barangay IV",
        "Barangay V",
        "Barangay VI",
        "Barangay VII",
        "Barangay VIII",
        "Barangay IX",
        "Barangay X",
        "Barangay XI",
        "Barangay XII",
        "Barangay XIII",
        "Barangay XIV",
        "Barangay XV",
        "Barangay XVI",
      ],
      Maragondon: [
        "Barangay I",
        "Barangay II",
        "Barangay III",
        "Barangay IV",
        "Barangay V",
        "Barangay VI",
        "Barangay VII",
        "Barangay VIII",
        "Barangay IX",
        "Barangay X",
        "Barangay XI",
        "Barangay XII",
        "Barangay XIII",
        "Barangay XIV",
        "Barangay XV",
        "Barangay XVI",
        "Barangay XVII",
        "Barangay XVIII",
        "Barangay XIX",
        "Barangay XX",
        "Barangay XXI",
        "Barangay XXII",
        "Barangay XXIII",
      ],
      Ternate: [
        "Barangay I",
        "Barangay II",
        "Barangay III",
        "Barangay IV",
        "Barangay V",
        "Barangay VI",
        "Barangay VII",
        "Barangay VIII",
        "Barangay IX",
        "Barangay X",
        "Barangay XI",
        "Barangay XII",
        "Barangay XIII",
        "Barangay XIV",
        "Barangay XV",
        "Barangay XVI",
      ],
    },
    Laguna: {
      "Calamba City": [
        "Bagong Kalsada",
        "Banadero",
        "Banlic",
        "Barandal",
        "Batino",
        "Bubuyan",
        "Bucal",
        "Bunggo",
        "Burol",
        "Camaligan",
        "Canlubang",
        "Halang",
        "Hornalan",
        "Kay-Anlog",
        "La Mesa",
        "Laguerta",
        "Lawa",
        "Lecheria",
        "Lingga",
        "Looc",
        "Mabato",
        "Makiling",
        "Mapagong",
        "Masili",
        "Maunong",
        "Mayapa",
        "Milagrosa",
        "Paciano Rizal",
        "Pansol",
        "Parian",
        "Poblacion",
        "Punta",
        "Puting Lupa",
        "Real",
        "Saimsim",
        "Sampiruhan",
        "San Cristobal",
        "San Jose",
        "San Juan",
        "Sirang Lupa",
        "Sucol",
        "Turbina",
        "Ulango",
        "Uwisan",
      ],
      "San Pedro City": [
        "Bagong Silang",
        "Calendola",
        "Chrysanthemum",
        "Cuyab",
        "Estrella",
        "G.S.I.S.",
        "Landayan",
        "Laram",
        "Magsaysay",
        "Maharlika",
        "Narra",
        "Nueva",
        "Pacita I",
        "Pacita II",
        "Poblacion",
        "Riverside",
        "Rosario",
        "Sampaguita Village",
        "San Antonio",
        "San Lorenzo Ruiz",
        "San Roque",
        "San Vicente",
        "Santo Niño",
        "United Bayanihan",
        "United Better Living",
      ],
      "Santa Rosa City": [
        "Aplaya",
        "Balibago",
        "Caingin",
        "Dila",
        "Dita",
        "Don Jose",
        "Ibaba",
        "Kanluran",
        "Labas",
        "Macabling",
        "Malusak",
        "Market Area",
        "Pooc",
        "Pulong Santa Cruz",
        "Santo Domingo",
        "Sinalhan",
        "Tagapo",
      ],
      "Biñan City": [
        "Biñan",
        "Bungahan",
        "Canlalay",
        "Casile",
        "De La Paz",
        "Ganado",
        "Langkiwa",
        "Loma",
        "Malaban",
        "Malamig",
        "Mamplasan",
        "Platero",
        "Poblacion",
        "San Antonio",
        "San Francisco",
        "San Jose",
        "San Vicente",
        "Santo Domingo",
        "Santo Niño",
        "Santo Tomas",
        "Soro-soro",
        "Timbao",
        "Tubigan",
        "Zapote",
      ],
      "Cabuyao City": [
        "Baclaran",
        "Banay-banay",
        "Banlic",
        "Bigaa",
        "Butong",
        "Casile",
        "Diezmo",
        "Gulod",
        "Mamatid",
        "Marinig",
        "Niugan",
        "Pittland",
        "Poblacion Dos",
        "Poblacion Tres",
        "Poblacion Uno",
        "Pulo",
        "Sala",
        "San Isidro",
      ],
      "San Pablo City": [
        "I-A",
        "I-B",
        "I-C",
        "II-A",
        "II-B",
        "II-C",
        "II-D",
        "II-E",
        "II-F",
        "III-A",
        "III-B",
        "III-C",
        "III-D",
        "III-E",
        "III-F",
        "IV-A",
        "IV-B",
        "IV-C",
        "V-A",
        "V-B",
        "V-C",
        "V-D",
        "VI-A",
        "VI-B",
        "VI-C",
        "VI-D",
        "VI-E",
        "VII-A",
        "VII-B",
        "VII-C",
        "VII-D",
        "VII-E",
        "Atisan",
        "Bagong Bayan",
        "Bagong Pook",
        "Balagbag",
        "Banago",
        "Bautista",
        "Concepcion",
        "Del Remedio",
        "Dolores",
        "San Antonio 1",
        "San Antonio 2",
        "San Bartolome",
        "San Buenaventura",
        "San Crispin",
        "San Cristobal",
        "San Diego",
        "San Francisco",
        "San Gabriel",
        "San Gregorio",
        "San Ignacio",
        "San Isidro",
        "San Joaquin",
        "San Jose",
        "San Juan",
        "San Lorenzo",
        "San Lucas 1",
        "San Lucas 2",
        "San Marcos",
        "San Mateo",
        "San Miguel",
        "San Nicolas",
        "San Pedro",
        "San Rafael",
        "San Roque",
        "San Vicente",
        "Santa Ana",
        "Santa Catalina",
        "Santa Cruz",
        "Santa Elena",
        "Santa Felomina",
        "Santa Isabel",
        "Santa Maria",
        "Santa Monica",
        "Santa Veronica",
        "Santiago I",
        "Santiago II",
        "Santisimo Rosario",
        "Santo Angel",
        "Santo Cristo",
        "Santo Niño",
      ],
      "Los Baños": [
        "Anos",
        "Bagong Silang",
        "Bambang",
        "Batong Malake",
        "Baybayin",
        "Bayog",
        "Lalakay",
        "Maahas",
        "Malinta",
        "Mayondon",
        "Poblacion",
        "Putho-Tuntungin",
        "San Antonio",
        "Tadlac",
        "Timugan",
      ],
      Bay: [
        "Bitin",
        "Calo",
        "Daniw",
        "Maitim",
        "Masaya",
        "Paciano Rizal",
        "Poblacion",
        "Puypuy",
        "San Antonio",
        "San Isidro",
        "San Nicolas",
        "Santa Cruz",
        "Tagumpay",
        "Tranca",
      ],
      Calauan: [
        "Balayhangin",
        "Bangyas",
        "Dayap",
        "Hanggan",
        "Imok",
        "Lamot 1",
        "Lamot 2",
        "Limao",
        "Mabacan",
        "Masiit",
        "Paliparan",
        "Perez",
        "Poblacion",
        "Prinza",
        "San Isidro",
        "Santo Tomas",
      ],
      Alaminos: [
        "Barangay I",
        "Barangay II",
        "Del Carmen",
        "Poblacion A",
        "Poblacion B",
        "San Agustin",
        "San Benito",
        "San Ildefonso",
        "San Miguel",
      ],
      "Santa Cruz": [
        "Alipit",
        "Bagumbayan",
        "Bubukal",
        "Calios",
        "Duhat",
        "Gatid",
        "Jasaan",
        "Labuin",
        "Malinao",
        "Oogong",
        "Pagsawitan",
        "Palasan",
        "Patimbao",
        "Poblacion 1",
        "Poblacion 2",
        "Poblacion 3",
        "Poblacion 4",
        "Poblacion 5",
        "San Jose",
        "San Juan",
        "San Pablo Norte",
        "San Pablo Sur",
        "Santisima Cruz",
      ],
      Pila: [
        "Aplaya",
        "Bagong Pook",
        "Bulilan Norte",
        "Bulilan Sur",
        "Concepcion",
        "Labuin",
        "Linga",
        "Masico",
        "Mojon",
        "Pansol",
        "Pinagbayanan",
        "Poblacion",
        "Sabang",
        "San Antonio",
        "Santa Clara Norte",
        "Santa Clara Sur",
      ],
      Victoria: [
        "Banca-banca",
        "Pinagbayanan",
        "Poblacion",
        "Sabang",
        "San Antonio",
        "Santa Clara Norte",
        "Santa Clara Sur",
      ],
      Victoria: ["Banca-banca", "Daniw", "Masapang", "Nanhaya", "Poblacion", "San Benito", "San Felix", "San Roque"],
      Rizal: ["Antipolo", "Entablado", "Laguan", "Paule 1", "Paule 2", "Poblacion", "Pook", "Tala", "Talaga", "Tuy"],
      Nagcarlan: [
        "Abo",
        "Alibungbungan",
        "Alilinan",
        "Balayong",
        "Balimbing",
        "Balinacon",
        "Bambang",
        "Banago",
        "Banca-banca",
        "Bangcuro",
        "Banilad",
        "Bayaquitos",
        "Buboy",
        "Buenavista",
        "Buhanginan",
        "Bukal",
        "Bunga",
        "Cabuyew",
        "Calumpang",
        "Kanluran",
        "Labangan",
        "Lawaguin",
        "Maiit",
        "Manaol",
        "Maravilla",
        "Nagcalbang",
        "Oples",
        "Palayan",
        "Poblacion 1",
        "Poblacion 2",
        "Poblacion 3",
        "Sabang",
        "Silangan",
        "Sulsuguin",
        "Talahib",
        "Talangan",
        "Taytay",
        "Tipacan",
        "Wakat",
        "Yukos",
      ],
      Liliw: [
        "Bagong Anyo",
        "Bayate",
        "Bongkol",
        "Bubukal",
        "Cabuyao",
        "Calumpang",
        "Culoy",
        "Dagatan",
        "Daniw",
        "Dita",
        "Ibabang Palina",
        "Ibabang San Roque",
        "Ilayang Palina",
        "Ilayang San Roque",
        "Kanlurang Bukal",
        "Laguan",
        "Luquin",
        "Malabo-Kalantukan",
        "Masikap",
        "Mojon",
        "Novaliches",
        "Oples",
        "Pag-asa",
        "Palina",
        "Poblacion",
        "Rizal",
        "San Isidro",
        "Silangang Bukal",
        "Tuy-Baanan",
      ],
      Majayjay: [
        "Amonoy",
        "Bakia",
        "Balanac",
        "Balayong",
        "Banilad",
        "Banti",
        "Bitaoy",
        "Botocan",
        "Bukal",
        "Burgos",
        "Coralao",
        "Gagalot",
        "Ibabang Banga",
        "Ibabang Bayucain",
        "Ilayang Banga",
        "Ilayang Bayucain",
        "May-It",
        "Munting Kawayan",
        "Olla",
        "Origuel",
        "Pangil",
        "Panglan",
        "Piit",
        "Poblacion",
        "Pook",
        "Suba",
        "Talortor",
        "Tanawan",
        "Taytay",
      ],
      Magdalena: [
        "Alipit",
        "Baanan",
        "Balanac",
        "Bucal",
        "Buenavista",
        "Bungkol",
        "Burlungan",
        "Cigaras",
        "Halayhayin",
        "Ibabang Atingay",
        "Ibabang Butnong",
        "Ilayang Atingay",
        "Ilayang Butnong",
        "Malinao",
        "Malvar",
        "Poblacion",
        "Sabang",
        "Salasad",
        "Tanawan",
        "Tipunan",
      ],
      Paete: [
        "Bagumbayan",
        "Bangkusay",
        "Ermita",
        "Ibaba del Norte",
        "Ibaba del Sur",
        "Ilaya del Norte",
        "Ilaya del Sur",
        "Maytoong",
        "Poblacion",
        "Quinale",
        "Wawa",
      ],
      Kalayaan: ["Longos", "Poblacion", "San Antonio", "San Juan"],
      Lumban: [
        "Bagong Silang",
        "Balimbingan",
        "Balubad",
        "Caliraya",
        "Concepcion",
        "Lewin",
        "Maracta",
        "Maytalang I",
        "Maytalang II",
        "Primera Parang",
        "Primera Pulo",
        "Salac",
        "Santo Niño",
        "Segunda Parang",
        "Segunda Pulo",
        "Wawa",
      ],
      Cavinti: [
        "Anglas",
        "Bangco",
        "Bukal",
        "Bulajo",
        "Cansuso",
        "Duhat",
        "Inao-Awan",
        "Kanluran Talaongan",
        "Labayo",
        "Layasin",
        "Lumot",
        "Mahipon",
        "Paowin",
        "Poblacion",
        "Sisilmin",
        "Silangan Talaongan",
        "Sumucab",
        "Tibatib",
        "Udia",
      ],
      Pagsanjan: [
        "Anibong",
        "Barangay I",
        "Barangay II",
        "Biñan",
        "Cabanbanan",
        "Calusiche",
        "Dingin",
        "Lambac",
        "Layugan",
        "Magdapio",
        "Maulawin",
        "Mendiola",
        "Pinagsanjan",
        "Sabang",
        "Sampaloc",
        "San Isidro",
      ],
      Luisiana: [
        "De La Paz",
        "Kulapi",
        "San Antonio",
        "San Diego",
        "San Isidro",
        "San Jose",
        "San Juan",
        "San Luis",
        "San Pablo",
        "San Pedro",
        "San Rafaél",
        "San Roque",
        "San Salvador",
        "Santo Domingo",
        "Santo Tomás",
        "Zone I",
        "Zone II",
        "Zone III",
        "Zone IV",
        "Zone V",
        "Zone VI",
        "Zone VII",
        "Zone VIII",
      ],
      Pangil: [
        "Balian",
        "Dambo",
        "Galalan",
        "Isla",
        "Mabato-Azufre",
        "Natividad",
        "Poblacion",
        "San Jose",
        "Sulib",
        "Tabugon",
      ],
      Pakil: [
        "Baño",
        "Burgos",
        "Casa Real",
        "Casinsin",
        "Dorado",
        "Gonzales",
        "Kabulusan",
        "Matikiw",
        "Poblacion",
        "Saray",
        "Taft",
        "Tavera",
      ],
      Siniloan: [
        "Acevida",
        "Bagumbarangay",
        "Buhay",
        "G. Redor",
        "Gen. Luna",
        "Halayhayin",
        "J. Lanuza",
        "Kapatalan",
        "Laguio",
        "Liyang",
        "Llavac",
        "Macatad",
        "Magsaysay",
        "Mayatba",
        "Mendiola",
        "P. Burgos",
        "Poblacion Norte",
        "Poblacion Sur",
        "Salubungan",
        "Wawa",
      ],
      "Santa Maria": [
        "Adia",
        "Bagong Pook",
        "Bagumbayan",
        "Bubucal",
        "Cabooan",
        "Coralan",
        "Cueva",
        "Inayapan",
        "Jose P. Rizal",
        "Jose P. Laurel",
        "Macasipac",
        "Masinao",
        "Matalino",
        "Parang ng Buho",
        "Poblacion Dos",
        "Poblacion Tres",
        "Poblacion Uno",
        "Talangka",
        "Tungkod",
      ],
      Mabitac: [
        "Amuyong",
        "Lambac",
        "Libis ng Nayon",
        "Lucong Butong",
        "Matalatala",
        "Nanguma",
        "Numero",
        "Paagahan",
        "Poblacion",
        "San Antonio",
        "San Miguel",
        "Sinagtala",
      ],
      Famy: [
        "Asana",
        "Bacong-Sigsigan",
        "Bagong Bayan",
        "Balitoc",
        "Banaba",
        "Batuhan",
        "Bulihan",
        "Cuebang Bato",
        "Damayan",
        "Kapatalan",
        "Kataypuanan",
        "Liyang",
        "Maate",
        "Magdalo",
        "Mayatba",
        "Minayutan",
        "Poblacion",
        "Salangbato",
      ],
    },
    Bataan: {
      "Balanga City": [
        "Bagong Silang",
        "Bagumbayan",
        "Cabog-Cabog",
        "Camacho",
        "Cataning",
        "Central",
        "Cupang North",
        "Cupang Proper",
        "Cupang West",
        "Dangcol",
        "Doña Francisca",
        "Ibayo",
        "Malabia",
        "Munting Batangas",
        "Poblacion",
        "Port Area",
        "Pto. Rivas Ibaba",
        "Pto. Rivas Itaas",
        "San Jose",
        "Sibacan",
        "Talisay",
        "Tanato",
        "Tenejero",
        "Tortugas",
        "Tuyo",
      ],
      Abucay: ["Bangkal", "Capitangan", "Gabon", "Laon", "Mabatang", "Omboy", "Poblacion", "Salian", "Wawa"],
      Bagac: [
        "Bagumbayan",
        "Binuangan",
        "Ibaba",
        "Pag-asa",
        "Parang",
        "Poblacion",
        "Quinawan",
        "Saysain",
        "Tabing-Ilog",
      ],
      Dinalupihan: [
        "Aquino",
        "Bangal",
        "Bayan-bayanan",
        "Bonifacio",
        "Burgos",
        "Colo",
        "Daang Bago",
        "Del Pilar",
        "Gen. Luna",
        "Happy Valley",
        "Jose C. Payumo Jr.",
        "Kataasan",
        "Layac",
        "Luacan",
        "Mabini",
        "Magsaysay",
        "Naparing",
        "New San Jose",
        "Old San Jose",
        "Padre Dandan",
        "Pag-asa",
        "Payangan",
        "Pentor",
        "Poblacion",
        "Pulo",
        "Rizal",
        "Roosevelt",
        "Roxas",
        "San Benito",
        "San Isidro",
        "San Pablo",
        "San Ramon",
        "Santo Niño",
        "Sapang Balas",
        "Torres",
        "Tucop",
        "Tuyo",
        "Zamora",
      ],
      Hermosa: [
        "A. Rivera",
        "Almacen",
        "Bacong",
        "Balsic",
        "Bamban",
        "Burgos-Soliman",
        "Cataning",
        "Culis",
        "Daungan",
        "Judge Roman Cruz Sr.",
        "Mabiga",
        "Maite",
        "Mambog-Mandama",
        "Palihan",
        "Pandatung",
        "Poblacion",
        "Pulo",
        "Saba",
        "Sacrifice Valley",
        "San Pedro",
        "Santo Cristo",
        "Sumalo",
        "Tipo",
      ],
      Limay: [
        "Alangan",
        "Duale",
        "Kitang I",
        "Kitang II & Luz",
        "Lamao",
        "Landing",
        "Poblacion",
        "Reformista",
        "Saint Francis II",
        "San Francisco de Asis",
        "Townsite",
        "Wawa",
      ],
      Mariveles: [
        "Alas-asin",
        "Alion",
        "Balon-anito",
        "Batangas II",
        "Biaan",
        "Cabcaben",
        "Camaya",
        "Ipag",
        "Lucanin",
        "Malaya",
        "Maligaya",
        "Poblacion",
        "San Carlos",
        "San Isidro",
        "Sisiman",
        "Talisay",
      ],
      Morong: ["Binaritan", "Mabayo", "Nagbalayong", "Poblacion", "Sabang"],
      Orani: [
        "Apollo",
        "Bagong Paraiso",
        "Balut",
        "Bayan",
        "Calero",
        "Centro I",
        "Centro II",
        "Dona",
        "Kaparangan",
        "Masantol",
        "Mulawin",
        "Pag-asa",
        "Palihan",
        "Pantalan Bago",
        "Pantalan Luma",
        "Parang Parang",
        "Poblacion",
        "Sibul",
        "Silahis",
        "Sukol",
        "Tagumpay",
        "Tala",
        "Talimundoc",
        "Tapulao",
        "Tenejero",
        "Tugatog",
        "Wawa",
      ],
      Orion: [
        "Arellano",
        "Bagumbayan",
        "Balagtas",
        "Bantan",
        "Bilolo",
        "Calungusan",
        "Camachile",
        "Daang Bago",
        "Daang Bilolo",
        "Daang Pare",
        "General Lim",
        "Kapunitan",
        "Lati",
        "Lusungan",
        "Puting Buhangin",
        "Sabatan",
        "San Vicente",
        "Santa Elena",
        "Santo Domingo",
        "Villa Angeles",
        "Wakas",
      ],
      Pilar: [
        "Bagumbayan",
        "Balut I",
        "Balut II",
        "Bantan",
        "Burgos",
        "Del Rosario",
        "Diwa",
        "Landing",
        "Liyang",
        "Nagwaling",
        "Panilao",
        "Pantingan",
        "Poblacion",
        "Rizal",
        "Santa Rosa",
        "Wakas",
      ],
      Samal: [
        "East Calaguiman",
        "East Daang Bago",
        "Gugo",
        "Ibaba",
        "Imelda",
        "Lalawigan",
        "Palili",
        "Poblacion",
        "San Juan",
        "San Roque",
        "Santa Lucia",
        "Sapa",
        "Tabing Ilog",
        "West Calaguiman",
        "West Daang Bago",
      ],
    },
    Rizal: {
      "Antipolo City": [
        "Bagong Nayon",
        "Beverly Hills",
        "Calawis",
        "Cupang",
        "Dalig",
        "dela Paz",
        "Inarawan",
        "Mayamot",
        "Muntindilaw",
        "San Isidro",
        "San Jose",
        "San Juan",
        "San Luis",
        "San Roque",
        "Santa Cruz",
        "Santo Niño",
        "Taktak",
      ],
      Angono: ["Bagumbayan", "Mahabang Parang", "Poblacion Ibaba", "Poblacion Itaas", "San Isidro", "San Pedro"],
      Baras: ["Evangelista", "Pinugay", "Poblacion", "Rizal", "San Jose", "San Miguel", "San Salvador"],
      Binangonan: [
        "Bilibiran",
        "Bombongan",
        "Buhangin",
        "Calumpang",
        "Darangan",
        "Gitnang Bayan I",
        "Gitnang Bayan II",
        "Guilib",
        "Ithan",
        "Janosa",
        "Kalinawan",
        "Kalumpang",
        "Kinaboogan",
        "Libis",
        "Mahabang Parang",
        "Malakaban",
        "Mambog",
        "Pantok",
        "Pila-pila",
        "Pipindan",
        "Poblacion",
        "Pook",
        "San Carlos",
        "Taboc",
        "Tatala",
        "Tayuman",
        "Totokan",
        "Tuktukan",
      ],
      Cainta: [
        "Dayap",
        "de la Paz",
        "Dollores",
        "Karangalan",
        "Manggahan",
        "Mayamot",
        "Poblacion",
        "San Andres",
        "San Isidro",
        "San Juan",
        "Santa Rosa",
      ],
      Cardona: ["Banca-banca", "Biga", "Busawe", "Poblacion 1", "Poblacion 2", "Poblacion 3"],
      "Jala-jala": [
        "Bagong Buhay I",
        "Bagong Buhay II",
        "Bagong Buhay III",
        "Bayugo",
        "Lubo",
        "Paalaman",
        "Poblacion",
        "Sipsipin",
      ],
      Morong: [
        "Bombongan",
        "Lagundi",
        "Maybancal",
        "Poblacion",
        "San Guillermo",
        "San Jose",
        "San Juan",
        "San Pedro",
        "Wawa",
      ],
      Pililla: [
        "Bagumbayan",
        "Bambang",
        "Bugana",
        "Bulihan",
        "Halayhayin",
        "Imatong",
        "Malaya",
        "Nangka",
        "Paete",
        "Poblacion",
        "San Antonio",
        "Quisao",
        "Sipsipin",
        "Tuklong",
        "Yambo",
      ],
      Rodriguez: [
        "Balite",
        "Burgos",
        "Geronimo",
        "Macabud",
        "Manggahan",
        "Mascap",
        "Poblacion",
        "Rosario",
        "San Isidro",
        "San Jose",
        "San Rafael",
      ],
      "San Mateo": [
        "Ampid I",
        "Ampid II",
        "Banaba",
        "Dulongbayan",
        "Guitnangbayan I",
        "Guitnangbayan II",
        "Malanday",
        "Maly",
        "Nangka",
        "Poblacion",
        "Silangan",
      ],
      Tanay: [
        "Cuyambay",
        "Daraitan",
        "General Luna",
        "Kaliwa",
        "Laiban",
        "Mahabang Parang",
        "Mayamot",
        "Poblacion",
        "Sampaloc",
        "San Andres",
        "San Isidro",
        "Santa Ines",
        "Tandang Kutyo",
      ],
      Taytay: ["Bagumbayan", "Dolores", "Muzon", "Poblacion", "San Isidro", "San Juan", "Santa Ana"],
      Teresa: ["Bagumbayan", "Dalig", "Dulumbayan", "Mayamot", "Poblacion", "Prinza", "San Roque"],
    },
    Quezon: {
      "Lucena City": [
        "Barangay 1",
        "Barangay 2",
        "Barangay 3",
        "Barangay 4",
        "Barangay 5",
        "Barangay 6",
        "Barangay 7",
        "Barangay 8",
        "Barangay 9",
        "Barangay 10",
        "Barangay 11",
        "Barra",
        "Bocohan",
        "Cotta",
        "Dalahican",
        "Domoit",
        "Gulang-Gulang",
        "Ibabang Dupay",
        "Ibabang Iyam",
        "Ibabang Talim",
        "Ilayang Dupay",
        "Ilayang Iyam",
        "Ilayang Talim",
        "Isabang",
        "Kanlurang Mayao",
        "Kulapi",
        "Mayao Castillo",
        "Mayao Crossing",
        "Mayao Kanluran",
        "Mayao Parada",
        "Ransohan",
        "Salinas",
        "Silangang Mayao",
      ],
      "Tayabas City": [
        "Angeles Zone I",
        "Angeles Zone II",
        "Angeles Zone III",
        "Angeles Zone IV",
        "Angustias Zone I",
        "Angustias Zone II",
        "Angustias Zone III",
        "Angustias Zone IV",
        "Ayaas",
        "Baguio",
        "Banilad",
        "Bukal",
        "Domoit Kanluran",
        "Domoit Silangan",
        "Gibanga",
        "Ibas",
        "Isabang",
        "Katigan Kanluran",
        "Katigan Silangan",
        "Lakawan",
        "Lita",
        "Malabanban Norte",
        "Malabanban Sur",
        "Masin",
        "Mate",
        "Mateuna",
        "Mayabobo",
        "Opias",
        "Palale",
        "Pandakaki",
        "Poblacion",
        "Potol",
        "San Diego Zone I",
        "San Diego Zone II",
        "San Diego Zone III",
        "San Diego Zone IV",
        "San Isidro Zone I",
        "San Isidro Zone II",
        "San Isidro Zone III",
        "San Isidro Zone IV",
        "San Roque Zone I",
        "San Roque Zone II",
        "Talolong",
        "Tamlong",
        "Walay",
      ],
      Candelaria: [
        "Buenavista",
        "Bukal",
        "Kinatihan I",
        "Kinatihan II",
        "Malabanban",
        "Mangilag Norte",
        "Mangilag Sur",
        "Masalukot I",
        "Masalukot II",
        "Masalukot III",
        "Masalukot IV",
        "Masalukot V",
        "Masin Norte",
        "Masin Sur",
        "Pahinga Norte",
        "Pahinga Sur",
        "Poblacion",
        "San Isidro",
      ],
      Sariaya: [
        "Antipolo del Norte",
        "Antipolo del Sur",
        "Bignay I",
        "Bignay II",
        "Bucal",
        "Castañas",
        "Concepcion Banahaw",
        "Concepcion Palasan",
        "Gibanga",
        "Guisguis Norte",
        "Guisguis Sur",
        "Limbon",
        "Manggalang Bantad",
        "Manggalang Kiling",
        "Morong",
        "Palaisdaan",
        "Poblacion Barangay I",
        "Poblacion Barangay II",
        "Poblacion Barangay III",
        "Poblacion Barangay IV",
        "Poblacion Barangay V",
        "Poblacion Barangay VI",
        "Sampaloc I",
        "Sampaloc II",
        "San Felipe",
        "San Francisco",
        "San Juan",
        "Talaan",
        "Tumbaga I",
        "Tumbaga II",
      ],
      Tiaong: [
        "Anastacia",
        "Aquino",
        "Ayusan I",
        "Ayusan II",
        "Behia",
        "Bukal",
        "Bula",
        "Bulakin",
        "Cabatang",
        "Cabay",
        "Del Rosario",
        "Lagalag",
        "Lalig",
        "Lumingon",
        "Lusacan",
        "Palagaran",
        "Poblacion I",
        "Poblacion II",
        "Poblacion III",
        "Poblacion IV",
        "San Agustin",
        "San Bartolome",
        "San Felix",
        "San Francisco",
        "San Isidro",
        "San Jose",
        "San Juan",
        "San Pedro",
        "San Vicente",
        "Santa Cruz",
      ],
      Dolores: [
        "Antonino",
        "Bahi",
        "Buenavista",
        "Bulihan",
        "Dagatan",
        "Dap-dap",
        "Kinabuhayan",
        "Maligaya",
        "Mangilag",
        "Masalukot",
        "Poblacion Zone I",
        "Poblacion Zone II",
        "Poblacion Zone III",
        "Poblacion Zone IV",
        "San Isidro",
        "Silangang Malicboy",
        "Sta. Catalina",
        "Sta. Maria",
        "Sumilang",
      ],
      "San Antonio": [
        "Bagong Silang",
        "Balibago",
        "Bulihan",
        "Magsaysay",
        "Mangilag",
        "Poblacion Zone I",
        "Poblacion Zone II",
        "Poblacion Zone III",
        "Poblacion Zone IV",
        "San Bartolome",
        "San Isidro",
        "San Vicente",
        "Santa Cruz",
        "Villa Esperanza",
      ],
      Pagbilao: [
        "Alupaye",
        "Biga",
        "Bukal Norte",
        "Bukal Sur",
        "Ibabang Polo",
        "Ilayang Polo",
        "Marao",
        "Pag-asa",
        "Poblacion Zone I",
        "Poblacion Zone II",
        "Poblacion Zone III",
        "Poblacion Zone IV",
        "Silangang Malicboy",
        "Wawa",
      ],
      "Padre Burgos": [
        "Burgos",
        "Duhat",
        "Kanlurang Calumpang",
        "Mabini",
        "Poblacion",
        "Rizal",
        "Silangang Calumpang",
        "Villa Ramos",
      ],
      Atimonan: [
        "Barangay Zone I",
        "Barangay Zone II",
        "Barangay Zone III",
        "Barangay Zone IV",
        "Caridad Ibaba",
        "Caridad Ilaya",
        "Kilogan",
        "Look 1st",
        "Look 2nd",
        "Luksuhin Ibaba",
        "Luksuhin Ilaya",
        "Magsaysay",
        "Pag-asa Ibaba",
        "Pag-asa Ilaya",
        "Pinagkamaligan",
        "Poblacion",
        "Salibungot",
        "San Andres Ibaba",
        "San Andres Ilaya",
        "San Isidro Ibaba",
        "San Isidro Ilaya",
        "Talipan",
        "Tignoan",
        "Villa Ibaba",
        "Villa Ilaya",
      ],
      Agdangan: [
        "Binagbag",
        "Dayap",
        "Ibabang Kinagunan",
        "Ilayang Kinagunan",
        "Kanlurang Calutan",
        "Poblacion",
        "Silangang Calutan",
        "Sildora",
        "Unisan",
      ],
      Unisan: [
        "Balanacan",
        "Bonifacio",
        "Buenasuerte",
        "Cabulihan",
        "General Luna",
        "Kalilayan",
        "Mabini",
        "Magsaysay",
        "Pagkakaisa",
        "Plaridel",
        "Poblacion I",
        "Poblacion II",
        "Punta",
        "Quezon",
        "Rizal",
        "San Roque",
        "Tubigan",
      ],
      Plaridel: [
        "Barangay I",
        "Barangay II",
        "Barangay III",
        "Barangay IV",
        "Barangay V",
        "Barangay VI",
        "Barangay VII",
        "Barangay VIII",
        "Barangay IX",
        "Barangay X",
        "Barangay XI",
        "Barangay XII",
        "Barangay XIII",
        "Barangay XIV",
        "Barangay XV",
        "Barangay XVI",
        "Barangay XVII",
        "Barangay XVIII",
        "Barangay XIX",
        "Barangay XX",
        "Barangay XXI",
      ],
      Gumaca: [
        "Bahi",
        "Binagbag",
        "Buensuceso",
        "Danlagan",
        "General Luna",
        "Ibabang Dupay",
        "Ilayang Dupay",
        "Magsaysay",
        "Poblacion I",
        "Poblacion II",
        "Poblacion III",
        "Poblacion IV",
        "Poblacion V",
        "Poblacion VI",
        "Poblacion VII",
        "Poblacion VIII",
        "San Diego I",
        "San Diego II",
        "San Vicente",
      ],
      Lopez: [
        "Barangay I",
        "Barangay II",
        "Barangay III",
        "Barangay IV",
        "Barangay V",
        "Barangay VI",
        "Barangay VII",
        "Barangay VIII",
        "Barangay IX",
        "Barangay X",
        "Barangay XI",
        "Barangay XII",
        "Barangay XIII",
        "Barangay XIV",
        "Barangay XV",
        "Barangay XVI",
        "Barangay XVII",
        "Barangay XVIII",
        "Barangay XIX",
        "Barangay XX",
        "Barangay XXI",
        "Barangay XXII",
        "Barangay XXIII",
        "Barangay XXIV",
        "Barangay XXV",
        "Barangay XXVI",
        "Barangay XXVII",
        "Barangay XXVIII",
        "Barangay XXIX",
        "Barangay XXX",
        "Barangay XXXI",
        "Barangay XXXII",
        "Barangay XXXIII",
        "Barangay XXXIV",
        "Barangay XXXV",
        "Barangay XXXVI",
        "Barangay XXXVII",
        "Barangay XXXVIII",
        "Barangay XXXIX",
        "Barangay XL",
        "Barangay XLI",
        "Barangay XLII",
        "Barangay XLIII",
        "Barangay XLIV",
        "Barangay XLV",
        "Barangay XLVI",
        "Barangay XLVII",
        "Barangay XLVIII",
        "Barangay XLIX",
        "Barangay L",
        "Barangay LI",
      ],
      Calauag: [
        "Barangay I",
        "Barangay II",
        "Barangay III",
        "Barangay IV",
        "Barangay V",
        "Barangay VI",
        "Barangay VII",
        "Barangay VIII",
        "Barangay IX",
        "Barangay X",
        "Barangay XI",
        "Barangay XII",
        "Barangay XIII",
        "Barangay XIV",
        "Barangay XV",
        "Barangay XVI",
        "Barangay XVII",
        "Barangay XVIII",
        "Barangay XIX",
        "Barangay XX",
        "Barangay XXI",
        "Barangay XXII",
        "Barangay XXIII",
        "Barangay XXIV",
        "Barangay XXV",
        "Barangay XXVI",
        "Barangay XXVII",
        "Barangay XXVIII",
        "Barangay XXIX",
        "Barangay XXX",
        "Barangay XXXI",
        "Barangay XXXII",
        "Barangay XXXIII",
        "Barangay XXXIV",
        "Barangay XXXV",
        "Barangay XXXVI",
        "Barangay XXXVII",
        "Barangay XXXVIII",
        "Barangay XXXIX",
      ],
      Guinayangan: [
        "Aluyon",
        "Bagong Silang",
        "Barangay I",
        "Barangay II",
        "Barangay III",
        "Barangay IV",
        "Barangay V",
        "Barangay VI",
        "Barangay VII",
        "Barangay VIII",
        "Barangay IX",
        "Barangay X",
        "Barangay XI",
        "Barangay XII",
        "Barangay XIII",
        "Barangay XIV",
        "Barangay XV",
        "Barangay XVI",
        "Barangay XVII",
        "Barangay XVIII",
        "Barangay XIX",
        "Barangay XX",
        "Barangay XXI",
        "Barangay XXII",
        "Barangay XXIII",
        "Barangay XXIV",
        "Barangay XXV",
        "Barangay XXVI",
        "Barangay XXVII",
        "Barangay XXVIII",
        "Barangay XXIX",
        "Barangay XXX",
        "Barangay XXXI",
        "Barangay XXXII",
        "Barangay XXXIII",
        "Barangay XXXIV",
        "Barangay XXXV",
        "Barangay XXXVI",
        "Barangay XXXVII",
        "Barangay XXXVIII",
        "Barangay XXXIX",
        "Barangay XL",
        "Barangay XLI",
        "Barangay XLII",
        "Barangay XLIII",
        "Barangay XLIV",
        "Barangay XLV",
        "Barangay XLVI",
        "Barangay XLVII",
        "Barangay XLVIII",
        "Barangay XLIX",
        "Barangay L",
        "Barangay LI",
        "Barangay LII",
        "Barangay LIII",
        "Barangay LIV",
        "Barangay LV",
        "Barangay LVI",
        "Barangay LVII",
        "Barangay LVIII",
        "Barangay LIX",
        "Barangay LX",
      ],
      Tagkawayan: [
        "Alupaye",
        "Bagong Silang I",
        "Bagong Silang II",
        "Bamban",
        "Bukal",
        "Crossing Ibaba",
        "Crossing Ilaya",
        "Del Rosario",
        "Katimo",
        "Kilago",
        "Laguio",
        "Mahinta",
        "Manato",
        "Mapulot",
        "Poblacion I",
        "Poblacion II",
        "Poblacion III",
        "Poblacion IV",
        "Poblacion V",
        "Poblacion VI",
        "Poblacion VII",
        "Poblacion VIII",
        "San Diego",
        "San Isidro",
        "San Pablo",
        "San Vicente",
        "Santa Monica",
      ],
      Buenavista: [
        "Bagong Silang",
        "Buli",
        "Magsaysay",
        "Poblacion I",
        "Poblacion II",
        "Poblacion III",
        "San Isidro",
        "San Vicente",
      ],
      "San Narciso": [
        "Andres Bonifacio",
        "Apad Talon",
        "Bani",
        "Bataan",
        "Binay",
        "Buenavista",
        "Cabatang",
        "Canaway",
        "Kabulihan",
        "Lamon",
        "Magsaysay",
        "Palale",
        "Poblacion",
        "Rizal",
        "San Isidro",
        "Santa Cruz",
        "Tulay na Lupa",
      ],
      Mulanay: [
        "Amot",
        "Apad",
        "Bolo",
        "Bukal",
        "Burgos",
        "Cambalo",
        "Ipil",
        "Magsaysay",
        "Poblacion I",
        "Poblacion II",
        "Poblacion III",
        "Poblacion IV",
        "Poblacion V",
        "San Isidro",
        "Santa Rosa",
      ],
      "San Francisco": [
        "Calumpang",
        "Huyon-uyon",
        "Magsaysay",
        "Poblacion I",
        "Poblacion II",
        "Poblacion III",
        "San Isidro",
        "Santa Catalina",
      ],
      "San Andres": [
        "Camflora",
        "Camohaguin",
        "Campalingo",
        "Camposanto",
        "Poblacion I",
        "Poblacion II",
        "Poblacion III",
        "San Isidro",
        "Santa Cruz",
      ],
      Jomalig: ["Apad", "Bukal", "Casuguran", "Poblacion", "Talisoy"],
      Patnanungan: ["Amaga", "Busdak", "Kilogan", "Luod", "Patnanungan Norte", "Patnanungan Sur"],
      Panukulan: ["Bagong Silang", "Kinamaligan", "Poblacion", "Panukulan"],
      Burdeos: ["Aluyon", "Amot", "Bonifacio", "Cabugao", "Carlagan", "Mabini", "Poblacion", "Rizal", "San Rafael"],
      "General Nakar": [
        "Anoling",
        "Banglos",
        "Batangan",
        "Cabulihan",
        "Canaway",
        "Mahabang Lalim",
        "Maigang",
        "Maligaya",
        "Minahan Norte",
        "Minahan Sur",
        "Pagsangahan",
        "Poblacion",
        "Sablang",
        "Umiray",
      ],
      Infanta: [
        "Abiawin",
        "Amuyong",
        "Anibong",
        "Antiqueña",
        "Bacong",
        "Banugao",
        "Binulasan",
        "Boboin",
        "Comon",
        "Dinahican",
        "Gumian",
        "Lual",
        "Magsaysay",
        "Miswa",
        "Poblacion I",
        "Poblacion II",
        "Poblacion III",
        "Silangan",
        "Tongohin",
      ],
      Real: [
        "Aluyon",
        "Cagsiay I",
        "Cagsiay II",
        "Cagsiay III",
        "Kiloloran",
        "Llavac",
        "Lubayat",
        "Malapad",
        "Maragondon",
        "Poblacion I",
        "Poblacion II",
        "Tignoan",
        "Ungos",
      ],
      Mauban: [
        "Anibong",
        "Balesin",
        "Barangay I",
        "Barangay II",
        "Barangay III",
        "Barangay IV",
        "Barangay V",
        "Barangay VI",
        "Barangay VII",
        "Barangay VIII",
        "Barangay IX",
        "Barangay X",
        "Barangay XI",
        "Barangay XII",
        "Barangay XIII",
        "Barangay XIV",
        "Barangay XV",
        "Barangay XVI",
        "Barangay XVII",
        "Barangay XVIII",
        "Barangay XIX",
        "Barangay XX",
        "Barangay XXI",
        "Barangay XXII",
        "Barangay XXIII",
        "Barangay XXIV",
        "Barangay XXV",
        "Barangay XXVI",
        "Barangay XXVII",
        "Barangay XXVIII",
        "Barangay XXIX",
        "Barangay XXX",
        "Barangay XXXI",
        "Barangay XXXII",
        "Barangay XXXIII",
        "Barangay XXXIV",
        "Barangay XXXV",
        "Barangay XXXVI",
        "Barangay XXXVII",
        "Barangay XXXVIII",
        "Barangay XXXIX",
        "Barangay XL",
        "Barangay XLI",
        "Barangay XLII",
      ],
      Sampaloc: [
        "Alupay",
        "Apitong",
        "Bataan",
        "Bayongon",
        "Ibabang Owain",
        "Ilayang Owain",
        "Kiling",
        "Poblacion I",
        "Poblacion II",
        "Poblacion III",
        "San Roque",
        "Sulong",
        "Tecpan",
      ],
      Lucban: [
        "Abang",
        "Ayusan",
        "Bagumbayan",
        "Bukal",
        "Caridad",
        "Colong",
        "Kulapi",
        "Malaking Ambling",
        "Munting Ambling",
        "Poblacion I",
        "Poblacion II",
        "Poblacion III",
        "San Luis",
        "Talipan",
        "Tinamnan",
      ],
      Majayjay: [
        "Amonoy",
        "Bakia",
        "Balanac",
        "Balayong",
        "Banilad",
        "Banti",
        "Bitaoy",
        "Botocan",
        "Bukal",
        "Burgos",
        "Coralao",
        "Gagalot",
        "Ibabang Banga",
        "Ibabang Bayucain",
        "Ilayang Banga",
        "Ilayang Bayucain",
        "May-It",
        "Munting Kawayan",
        "Olla",
        "Origuel",
        "Pangil",
        "Panglan",
        "Piit",
        "Poblacion",
        "Pook",
        "Suba",
        "Talortor",
        "Tanawan",
        "Taytay",
      ],
      Alabat: [
        "Bacong",
        "Barangay I",
        "Barangay II",
        "Barangay III",
        "Barangay IV",
        "Barangay V",
        "Barangay VI",
        "Barangay VII",
        "Barangay VIII",
        "Barangay IX",
        "Barangay X",
        "Barangay XI",
        "Barangay XII",
        "Barangay XIII",
        "Barangay XIV",
        "Barangay XV",
        "Barangay XVI",
        "Barangay XVII",
        "Barangay XVIII",
        "Barangay XIX",
        "Barangay XX",
        "Barangay XXI",
        "Barangay XXII",
        "Barangay XXIII",
        "Barangay XXIV",
        "Barangay XXV",
        "Barangay XXVI",
        "Barangay XXVII",
        "Barangay XXVIII",
        "Barangay XXIX",
        "Barangay XXX",
      ],
      Perez: ["Bagong Silang", "Bantad", "Bukal", "Magsaysay", "Poblacion", "San Isidro", "Villa Padua"],
      Quezon: [
        "Apad",
        "Barangay I",
        "Barangay II",
        "Barangay III",
        "Barangay IV",
        "Barangay V",
        "Barangay VI",
        "Barangay VII",
        "Barangay VIII",
        "Barangay IX",
        "Barangay X",
        "Barangay XI",
        "Barangay XII",
        "Barangay XIII",
        "Barangay XIV",
        "Barangay XV",
        "Barangay XVI",
        "Barangay XVII",
        "Barangay XVIII",
        "Barangay XIX",
        "Barangay XX",
        "Barangay XXI",
        "Barangay XXII",
        "Barangay XXIII",
        "Barangay XXIV",
        "Barangay XXV",
        "Barangay XXVI",
        "Barangay XXVII",
        "Barangay XXVIII",
        "Barangay XXIX",
        "Barangay XXX",
        "Barangay XXXI",
        "Barangay XXXII",
        "Barangay XXXIII",
        "Barangay XXXIV",
        "Barangay XXXV",
        "Barangay XXXVI",
        "Barangay XXXVII",
        "Barangay XXXVIII",
        "Barangay XXXIX",
      ],
      Pitogo: ["Biga", "Malaking Patag", "Munting Patag", "Poblacion I", "Poblacion II", "Poblacion III", "San Isidro"],
      Macalelon: ["Bagong Silang", "Bantad", "Bukal", "Magsaysay", "Poblacion", "San Isidro", "Villa Padua"],
      "General Luna": ["Bagong Silang", "Bantad", "Bukal", "Magsaysay", "Poblacion", "San Isidro", "Villa Padua"],
      Catanauan: [
        "Bagong Silang Ibaba",
        "Bagong Silang Ilaya",
        "Biga",
        "Bukal",
        "Dahican",
        "Magsaysay",
        "Poblacion I",
        "Poblacion II",
        "Poblacion III",
        "San Isidro",
      ],
    },
  },
}

// Initialize location dropdowns
function initializeLocationDropdowns() {
  // Find all location dropdown containers
  const locationContainers = document.querySelectorAll('[id*="location-region"], .location-region')

  locationContainers.forEach((regionSelect) => {
    // Set up region dropdown
    populateRegions(regionSelect)

    // Find related dropdowns
    const container = regionSelect.closest(".mb-3") || regionSelect.parentElement
    const provinceSelect = container.querySelector('.location-province, [id*="location-province"]')
    const citySelect = container.querySelector('.location-city, [id*="location-city"]')
    const barangaySelect = container.querySelector('.location-barangay, [id*="location-barangay"]')
    const hiddenLocationField = container.querySelector('.full-location, [id*="farm-location-field"]')

    // Set up event listeners
    if (provinceSelect && citySelect && barangaySelect) {
      setupLocationEventListeners(regionSelect, provinceSelect, citySelect, barangaySelect, hiddenLocationField)
    }
  })
}

// Populate regions dropdown
function populateRegions(regionSelect) {
  // Clear existing options except the first one
  regionSelect.innerHTML = '<option value="">Select Region</option>'

  // Add all regions
  Object.keys(philippineLocations).forEach((region) => {
    const option = document.createElement("option")
    option.value = region
    option.textContent = region
    regionSelect.appendChild(option)
  })
}

// Set up event listeners for cascading dropdowns
function setupLocationEventListeners(regionSelect, provinceSelect, citySelect, barangaySelect, hiddenLocationField) {
  // Region change event
  regionSelect.addEventListener("change", function () {
    const selectedRegion = this.value

    // Reset dependent dropdowns
    resetDropdown(provinceSelect, "Select Province")
    resetDropdown(citySelect, "Select City/Municipality")
    resetDropdown(barangaySelect, "Select Barangay")

    // Always keep enabled
    provinceSelect.disabled = false;
    citySelect.disabled = false;
    barangaySelect.disabled = false;

    if (selectedRegion && philippineLocations[selectedRegion]) {
      populateProvinces(provinceSelect, selectedRegion)
    }

    updateHiddenLocationField(regionSelect, provinceSelect, citySelect, barangaySelect, hiddenLocationField)
  })

  // Province change event
  provinceSelect.addEventListener("change", function () {
    const selectedRegion = regionSelect.value
    const selectedProvince = this.value

    // Reset dependent dropdowns
    resetDropdown(citySelect, "Select City/Municipality")
    resetDropdown(barangaySelect, "Select Barangay")

    // Always keep enabled
    citySelect.disabled = false;
    barangaySelect.disabled = false;

    if (selectedRegion && selectedProvince && philippineLocations[selectedRegion][selectedProvince]) {
      populateCities(citySelect, selectedRegion, selectedProvince)
    }

    updateHiddenLocationField(regionSelect, provinceSelect, citySelect, barangaySelect, hiddenLocationField)
  })

  // City change event
  citySelect.addEventListener("change", function () {
    const selectedRegion = regionSelect.value
    const selectedProvince = provinceSelect.value
    const selectedCity = this.value

    // Reset barangay dropdown
    resetDropdown(barangaySelect, "Select Barangay")

    // Always keep enabled
    barangaySelect.disabled = false;

    if (
      selectedRegion &&
      selectedProvince &&
      selectedCity &&
      philippineLocations[selectedRegion][selectedProvince][selectedCity]
    ) {
      populateBarangays(barangaySelect, selectedRegion, selectedProvince, selectedCity)
    }

    updateHiddenLocationField(regionSelect, provinceSelect, citySelect, barangaySelect, hiddenLocationField)
  })

  // Barangay change event
  barangaySelect.addEventListener("change", () => {
    updateHiddenLocationField(regionSelect, provinceSelect, citySelect, barangaySelect, hiddenLocationField)
  })
}

// Populate provinces dropdown
function populateProvinces(provinceSelect, region) {
  const provinces = Object.keys(philippineLocations[region])
  provinces.forEach((province) => {
    const option = document.createElement("option")
    option.value = province
    option.textContent = province
    provinceSelect.appendChild(option)
  })
}

// Populate cities dropdown
function populateCities(citySelect, region, province) {
  const cities = Object.keys(philippineLocations[region][province])
  cities.forEach((city) => {
    const option = document.createElement("option")
    option.value = city
    option.textContent = city
    citySelect.appendChild(option)
  })
}

// Populate barangays dropdown
function populateBarangays(barangaySelect, region, province, city) {
  const barangays = philippineLocations[region][province][city]
  barangays.forEach((barangay) => {
    const option = document.createElement("option")
    option.value = barangay
    option.textContent = barangay
    barangaySelect.appendChild(option)
  })
}

// Reset dropdown to initial state
function resetDropdown(selectElement, placeholder) {
  selectElement.innerHTML = `<option value="">${placeholder}</option>`
  selectElement.disabled = false;
}

// Update hidden location field with full address
function updateHiddenLocationField(regionSelect, provinceSelect, citySelect, barangaySelect, hiddenLocationField) {
  if (!hiddenLocationField) return

  const region = regionSelect.value
  const province = provinceSelect.value
  const city = citySelect.value
  const barangay = barangaySelect.value

  // Build full address
  let fullAddress = ""
  if (barangay) fullAddress += barangay
  if (city) fullAddress += (fullAddress ? ", " : "") + city
  if (province) fullAddress += (fullAddress ? ", " : "") + province
  if (region) fullAddress += (fullAddress ? ", " : "") + region

  hiddenLocationField.value = fullAddress
}

// Function to set location dropdowns from a full address string
function setLocationFromString(container, locationString) {
  if (!locationString) return

  const regionSelect = container.querySelector('.location-region, [id*="location-region"]')
  const provinceSelect = container.querySelector('.location-province, [id*="location-province"]')
  const citySelect = container.querySelector('.location-city, [id*="location-city"]')
  const barangaySelect = container.querySelector('.location-barangay, [id*="location-barangay"]')

  // Try to parse the location string
  const parts = locationString.split(",").map((part) => part.trim())

  if (parts.length >= 4) {
    const [barangay, city, province, region] = parts

    // Set region
    if (regionSelect && philippineLocations[region]) {
      regionSelect.value = region
      regionSelect.dispatchEvent(new Event("change"))

      setTimeout(() => {
        // Set province
        if (provinceSelect && philippineLocations[region][province]) {
          provinceSelect.value = province
          provinceSelect.dispatchEvent(new Event("change"))

          setTimeout(() => {
            // Set city
            if (citySelect && philippineLocations[region][province][city]) {
              citySelect.value = city
              citySelect.dispatchEvent(new Event("change"))

              setTimeout(() => {
                // Set barangay
                if (barangaySelect && philippineLocations[region][province][city].includes(barangay)) {
                  barangaySelect.value = barangay
                  barangaySelect.dispatchEvent(new Event("change"))
                }
              }, 100)
            }
          }, 100)
        }
      }, 100)
    }
  }
}

// Initialize when DOM is loaded
document.addEventListener("DOMContentLoaded", () => {
  initializeLocationDropdowns()
})

// Re-initialize when modals are shown
document.addEventListener("shown.bs.modal", (event) => {
  const modal = event.target
  if (modal.id === "addAlternativeModal" || modal.id === "editFixedPineappleModal") {
    setTimeout(() => {
      initializeLocationDropdowns()
    }, 100)
  }
})

// Export functions for use in other scripts
window.LocationHandler = {
  initializeLocationDropdowns,
  setLocationFromString,
  philippineLocations,
}
